# Generated by Django 4.2.5 on 2023-09-16 20:00

from django.db import migrations, models
import music.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rock', 'Rock'), ('pop music', 'Pop Music'), ('hip hop', 'Hip Hop'), ('country', 'Country'), ('pop rap', 'Pop Rap'), ('folk music', 'Folk Music'), ('theme song', 'Theme song'), ('world music', 'World Music'), ('gospel', 'gospel'), ('funk', 'Funk')], max_length=200)),
                ('cover_img', models.ImageField(upload_to=music.utils.music_img)),
                ('singer_name', models.CharField(max_length=200)),
            ],
        ),
    ]
