# Generated by Django 4.2.5 on 2023-09-17 15:56

from django.db import migrations, models
import music.utils


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='audio_file',
            field=models.FileField(default='', upload_to=music.utils.audio_file),
            preserve_default=False,
        ),
    ]
