# Generated by Django 4.2.5 on 2023-09-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicmodel_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
