# Generated by Django 4.2.5 on 2023-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicmodel_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('punjabi', 'Punjabi'), ('malayalam', 'Malayalam'), ('telugu', 'Telugu')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
